use sha2::{Digest, Sha256};

use crate::config::Fragment;
use crate::error::Result;
use crate::ports::Fsys;
use crate::render::{Rendered, SecretLookup, Vars, render};

pub const MARKER: &str = "# generated by dotfix — edit sets/*/shell/ instead";
pub const CHECKSUM_PREFIX: &str = "# dotfix-checksum: ";
const TRAILER: &str = "[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local";

pub fn checksum(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Concatenate the active sets' shell fragments into a complete `.zshrc`.
///
/// Order is decided in [`crate::config::Repo::resolve`] and preserved here —
/// the Powerlevel10k instant-prompt block must stay at the very top.
pub fn generate(
    fragments: &[Fragment],
    fs: &dyn Fsys,
    vars: &Vars,
    secrets: &dyn SecretLookup,
) -> Result<Rendered> {
    let mut body = String::new();
    let mut contains_secrets = false;
    let mut secret_values: Vec<String> = Vec::new();

    for fragment in fragments {
        let source = fs.read(&fragment.path)?;
        let rendered = render(&fragment.path, &source, vars, secrets)?;
        body.push_str(&format!("# --- {}/{} ---\n", fragment.set, fragment.name));
        body.push_str(rendered.content.trim_end());
        body.push_str("\n\n");
        contains_secrets |= rendered.contains_secrets;
        secret_values.extend(rendered.secret_values);
    }
    secret_values.sort();
    secret_values.dedup();

    body.push_str(TRAILER);
    body.push('\n');

    let content = format!("{MARKER}\n{CHECKSUM_PREFIX}{}\n\n{body}", checksum(&body));

    Ok(Rendered {
        content,
        contains_secrets,
        secret_values,
    })
}

/// Everything after the two header lines and the blank line separating them.
pub fn body_of(generated: &str) -> Option<&str> {
    let (_, rest) = generated.split_once('\n')?;
    let (checksum_line, rest) = rest.split_once('\n')?;
    checksum_line.starts_with(CHECKSUM_PREFIX).then_some(())?;
    rest.strip_prefix('\n')
}

pub fn recorded_checksum(generated: &str) -> Option<&str> {
    generated.lines().nth(1)?.strip_prefix(CHECKSUM_PREFIX)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    use super::*;
    use crate::config::Fragment;
    use crate::error::Error;
    use crate::ports::fake::FakeFsys;
    use crate::render::{NoSecrets, SecretLookup, Vars};

    struct StaticSecrets;

    impl SecretLookup for StaticSecrets {
        fn get(&self, name: &str) -> Result<String> {
            match name {
                "api_key" => Ok("s3cr3t".to_string()),
                other => Err(Error::Secret {
                    name: other.to_string(),
                    reason: "not configured".to_string(),
                }),
            }
        }
    }

    fn vars() -> Vars {
        Vars {
            home: PathBuf::from("/Users/test"),
            user: "test".into(),
            machine: "box-one".into(),
            extra: BTreeMap::new(),
        }
    }

    fn fragments() -> Vec<Fragment> {
        vec![
            Fragment {
                set: "core".into(),
                name: "00-first.zsh".into(),
                path: PathBuf::from("/repo/sets/core/shell/00-first.zsh"),
            },
            Fragment {
                set: "web".into(),
                name: "10-web.zsh".into(),
                path: PathBuf::from("/repo/sets/web/shell/10-web.zsh"),
            },
        ]
    }

    fn fs() -> FakeFsys {
        FakeFsys::from([
            ("/repo/sets/core/shell/00-first.zsh", "# instant prompt\n"),
            ("/repo/sets/web/shell/10-web.zsh", "export W={{ home }}/w\n"),
        ])
    }

    #[test]
    fn concatenates_fragments_in_order_with_provenance_headers() {
        let out = generate(&fragments(), &fs(), &vars(), &NoSecrets)
            .unwrap()
            .content;
        let first = out.find("# instant prompt").unwrap();
        let second = out.find("export W=").unwrap();
        assert!(first < second, "fragment order must be preserved");
        assert!(out.contains("# --- core/00-first.zsh ---"));
        assert!(out.contains("# --- web/10-web.zsh ---"));
    }

    #[test]
    fn renders_templates_inside_fragments() {
        let out = generate(&fragments(), &fs(), &vars(), &NoSecrets)
            .unwrap()
            .content;
        assert!(out.contains("export W=/Users/test/w"));
        assert!(!out.contains("{{ home }}"));
    }

    #[test]
    fn starts_with_the_marker_and_a_checksum_of_the_body() {
        let out = generate(&fragments(), &fs(), &vars(), &NoSecrets)
            .unwrap()
            .content;
        assert!(out.starts_with(MARKER));
        let body = body_of(&out).unwrap();
        assert_eq!(recorded_checksum(&out).unwrap(), checksum(body));
    }

    #[test]
    fn ends_with_the_local_escape_hatch() {
        let out = generate(&fragments(), &fs(), &vars(), &NoSecrets)
            .unwrap()
            .content;
        assert!(
            out.trim_end()
                .ends_with("[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local")
        );
    }

    #[test]
    fn a_hand_edit_breaks_the_recorded_checksum() {
        let out = generate(&fragments(), &fs(), &vars(), &NoSecrets)
            .unwrap()
            .content;
        let tampered = format!("{out}\nalias sneaky=1\n");
        let body = body_of(&tampered).unwrap();
        assert_ne!(recorded_checksum(&tampered).unwrap(), checksum(body));
    }

    #[test]
    fn a_fragment_resolving_a_secret_flags_the_result_and_carries_the_value() {
        let fragments = vec![Fragment {
            set: "infra".into(),
            name: "20-secret.zsh".into(),
            path: PathBuf::from("/repo/sets/infra/shell/20-secret.zsh"),
        }];
        let fs = FakeFsys::from([(
            "/repo/sets/infra/shell/20-secret.zsh",
            "export TOKEN={{ secret(\"api_key\") }}\n",
        )]);
        let out = generate(&fragments, &fs, &vars(), &StaticSecrets).unwrap();
        assert!(
            out.contains_secrets,
            "must be flagged so .zshrc is written 0600"
        );
        assert_eq!(out.secret_values, vec!["s3cr3t".to_string()]);
    }

    #[test]
    fn fragments_without_secrets_carry_none() {
        let out = generate(&fragments(), &fs(), &vars(), &NoSecrets).unwrap();
        assert!(!out.contains_secrets);
        assert!(out.secret_values.is_empty());
    }
}
